# Generated by Django 5.2.4 on 2025-07-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dishordertable_remove_orderitem_dish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInputDishTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dishname', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('calorie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbon_emission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
