# Generated by Django 5.2.4 on 2025-07-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugar_added', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'nutrition_records',
            },
        ),
    ]
