# Generated by Django 5.2.4 on 2025-07-20 13:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='菜品名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='菜品描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='热量 (kcal)')),
                ('protein', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='蛋白质 (g)')),
                ('image_path', models.CharField(max_length=255, verbose_name='图片路径')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'db_table': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下单时间')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总价')),
                ('status', models.CharField(choices=[('Pending', '待处理'), ('Preparing', '准备中'), ('Completed', '已完成'), ('Cancelled', '已取消')], default='Pending', max_length=10, verbose_name='订单状态')),
            ],
            options={
                'verbose_name': '顾客订单',
                'verbose_name_plural': '顾客订单',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sugar_added', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='下单时单价')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dish', verbose_name='菜品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.order', verbose_name='所属订单')),
            ],
            options={
                'db_table': 'nutrition_records',
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
    ]
