# Generated by Django 5.2.4 on 2025-07-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishOrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.TextField()),
                ('image_url', models.URLField(max_length=500)),
                ('allergens', models.CharField(blank=True, max_length=100)),
                ('total_calorie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_carbon_emission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_fat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_carbohydrate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
