# Generated by Django 5.2.4 on 2025-07-20 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userinputdishtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinputdishtable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='下单时间'),
            preserve_default=False,
        ),
    ]
